### ISSUE TITLE
Dropbox cannot be used in heroku

### ISSUE THREAD

**Issue by iiowoii** [SirDankenstien/PaperMC-on-Heroku#1]
Dropbox cannot be used in heroku

![FAP{%%)S%{8ZL~@P)6PZZLJ](https://user-images.githubusercontent.com/60783918/103535657-15bdfe80-4ecc-11eb-9743-7f1e23627876.jpg)

**Comment by iiowoii** [comment]
Hope to update the new method
![GCK}BDF QT9MRB97K_ Y{EL](https://user-images.githubusercontent.com/60783918/103535904-882ede80-4ecc-11eb-8713-7b02ed9c6148.png)
![33ZP(L0_BU5T9%IEMWO_`OE](https://user-images.githubusercontent.com/60783918/103535909-8bc26580-4ecc-11eb-9edd-3a2ac5d65a4d.png)
![LGQV$}29V R4AJ HO6M1}}X](https://user-images.githubusercontent.com/60783918/103535931-92e97380-4ecc-11eb-8e94-d8a4ae6b3989.gif)

**Comment by SirDankenstien** [comment]
updated, does not require dropbox.
