### ISSUE TITLE
File Already in installed!!

### ISSUE THREAD

**Issue by HKSinha510** [SirDankenstien/PaperMC-on-Heroku#2]
Hello there!!
When i gone to `https://minecraft5100.herokuapp.com/panel/install.php` and click on register & install, it gave me a message saying that **MCGG has already been installed**![isse1](https://user-images.githubusercontent.com/83366038/119025056-5fae0980-b9c1-11eb-82db-8872921241ff.PNG), when i check the folder in the dropbox, they were alll empty, so how do i fix this?
![isse2](https://user-images.githubusercontent.com/83366038/119025113-6f2d5280-b9c1-11eb-83fd-85e884b0b6b5.PNG)

**Comment by SirDankenstien** [comment]
if it says MCGG has been installed, go to https://minecraft5100.herokuapp.com/panel/ and login with the credentials that you provided.

**Comment by HKSinha510** [comment]
ok, it worked now
thank you
